#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 28 11:48:43 2023
The Nature of Code
Daniel Shiffman
http://natureofcode.com
@author (java python conversion): evgeniy
"""


class Rule:
    def __init__(self, a, b):
        self.a = a
        self.b = b

    def getA():
        return self.a

    def getB():
        return self.b
