#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 28 11:25:20 2023

@author: evgeniy
"""
import py5

current = "A"
# Number of  generations
count = 0
text_height = 20

def setup():
    py5.size(200, 200)
    print("Generation " + str(count) + ": " + current)


def draw():
    py5.background(255)
    py5.fill(0)
    py5.text("Click mouse to generate", 10, py5.height - 20)
    #py5.no_loop()


def mouse_clicked():
    global current, count
    # A new StringBuffer for the next generation
    next_gen = []
    # Look through the current String to replace according to L-System rules
    for i in range(len(current)):
        c = current[i]
        if c == "A":
            # If we find A replace with AB
            next_gen.append("AB")
        elif c == "B":
            # If we find B replace with A
            next_gen.append("A")
    # The current String is now the next one
    current = "".join(next_gen)
    count += 1
    # Print to message console
    #py5.text("Generation " + str(count) + ": " + current, 10, text_height)
    #text_height += 20
    
    print("Generation " + str(count) + ": " + current)


py5.run_sketch()
